environment:
  matrix:
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.0"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install -r requirements.txt"
  - "pip install pyinstaller"

build_script:
  - "pyinstaller --name=makestack --onefile makestack/__main__.py"
  - SET ZIP=makestack-%APPVEYOR_REPO_TAG_NAME%-windows.zip
  - SET ZIP_DIR=makestack-%APPVEYOR_REPO_TAG_NAME%
  - mkdir %ZIP_DIR%
  - cp dist\makestack.exe %ZIP_DIR%
  - 7z a %ZIP% %ZIP_DIR%

artifacts:
  - path: "*.zip"
    name: MakeStack CLI for Windows

deploy:
  provider: GitHub
  auth_token:
    secure: "EXEQzZdMY88qHnSOpHCtyvuTmYa1VKPRK6Ysbp9EVOhvR2embyFKeIKja+GNilj/"
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true

