notifications:
  on_success: change
  on_failure: change

sudo: required
services:
  - docker
  - postgresql
  - redis-server

addons:
  code_climate:
    repo_token:
      secure: "MwQr5qEvy3Q9WJmT+IU+/qSabdFEtqWqqVlLLZB8ltKy/b4X9exyNf79kEZvnWlQy+bhCGNl8leEc6EHuRkCLuVhpARpG4vQciquYU49dN1ofgzREvqB3X0I9ujgxhKCrr15JTBNzIQR9ftbohcgylt/mHOchrsFumtqqT4/V9Ip5Xg4GJ1DFNNnDT6bP9X5N4uPSUXwd03qhoLn0SlhorlkfwWbI5e6gmIt9XVjNDZzA0DzBYVOgxfFQWROgHsjxRAQwv3gp6YEJnX6MM/bxjTfxv3dDvi5xSo2zLNnpMjYDeBi2+ZlOAsjcOfp8RSKVDsW3EHMrDBKmrV8rf2wzxNzDQpIyOTx75202ZWd4QirQZ86/R2nKnDXR6KwoYSLS3JFi2UUS3t97Gg/yOrswfLD4EzbcrKKN3fSiB+ySiWxvElsDzddzyyWzuTW8qtcGwQ4X1S04yV2tAvvAfvBD/GDRS+Zgp9oAOSlQwltHdYgFn6J608AVxaDK/uP6UjU8odoM6q8ePCQYbXABuOrCPTvmHu7KsmMF5HIKhVYptRgAZHOFSzTT3lCWcGqEYbr/t9nZG4PdRsmN9u4r4qqgZR3w2WuHXxzOEDwHPsYKFLj0L0ALaLCp39q/6WH/QFg9olILaMYW3SfJDTX6u9Dp4OfxXIvNWKw7Jh9PPRhZW4="

matrix:
  include:
    - os: linux
      language: python
      dist: trusty
      python: 3.5
    - os: linux
      language: python
      python: nightly
    - os: osx
      osx_image: xcode8.2
      language: generic
  allow_failures:
    - python: nightly

install:
  - "if [[ $TRAVIS_OS_NAME == osx ]]; then brew update; brew install ruby python3 postgresql redis; fi"
  - pip3 install -r requirements.txt
  - pip3 install -r test-requirements.txt

before_script:
  - "if [[ $TRAVIS_OS_NAME == linux ]]; then ./ci/setup; fi"

script:
  - "if [[ $TRAVIS_OS_NAME == linux ]]; then ./ci/run; fi"
  - make build

after_script:
  - "if [[ $TRAVIS_OS_NAME == "3.5" && $TRAVIS_OS_NAME == "linux" ]]; then codeclimate-test-reporter; fi"

before_deploy:
  - mkdir makestack-$TRAVIS_TAG
  - cp dist/makestack makestack-$TRAVIS_TAG
  - tar cf makestack-$TRAVIS_TAG-$TRAVIS_OS_NAME.tar.gz makestack-$TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: "NNmLDhiPqFX8o7mPqnmLaYUQBlwIDO/WLWnAQLGG6B7mH+r1Ac1ETrJzIlbXQa6gif6yMOXKAyjx+wT0x1tAfRa0RCQoqHvMkdojgZOUOQHBvqNhVbOeDLb7xEKdDEhPkt6dH+9bUxpcFgg1wBEIDvalc64i9HElmH5uhEEi44QbWYTAAkywwSvCwwu19+RACpRFcZP7BW/d6/u+MnZe2Guf5kkrHG+6Thplec6dXKw3biEQOEQrtLaFNpWBwa6gG7DamAsy5531Apu0mgAPPe8H2hNf4CBSG7yGlYnRoa1A/daGCV23yfR5QNDdDxWoNhNtzK6ewbOURM7aDPLd+P452NoH2YMO6kT5K6aaSCzpr9mhWUyO922qvc7333immMBLpL+1om6TSIhKL3kM4lrq6DZFPilKfVPAhYFl+nFrMSZ2D2c7NC+bRA6dUKgCwAqa05uVV8GM8jjCe66NhpmMkQTi3V56XuokNSSP6enE7Du1+GAQuxIMZj1PTCHDFio5I8J5me0JuPqxdCy+JmqnUiqJsg2kDOUBs9lQjrwaqGnB3RtEDKtsbkbI2tHOGtAPP2ZH91vjsu8ylbben6CUle4z6HxcncOGHJQyAPBk9WNz0mCCzNJ5HzY+V/yQlz6hE/4ovknlhZ5fv7CVd6wRsWzJZkaMseG4jin2ONo="
  file: makestack-$TRAVIS_TAG-$TRAVIS_OS_NAME.tar.gz
  skip_cleanup: true
  on:
    tags: true
    condition: '$TRAVIS_OS_NAME == "3.5" || $TRAVIS_OS_NAME == "osx"'
