matrix:
  include:
    - os: linux
      language: python
      python: 3.4
    - os: linux
      language: python
      python: 3.5
    - os: linux
      language: python
      python: nightly
    - os: osx
      language: generic
  allow_failures:
    - python: nightly


install:
  - "if [[ $TRAVIS_OS_NAME == osx ]]; then brew update; brew install python3; fi"
  - pip3 install -r requirements.txt
  - pip3 install pytest
  - git clone --depth 1 https://github.com/pyinstaller/pyinstaller
  - cd pyinstaller && python3 setup.py install && cd ..

script:
  - pyinstaller --name=makestack --onefile makestack/__main__.py
  - cp dist/makestack makestack-$TRAVIS_OS_NAME

deploy:
  provider: releases
  api_key:
    secure:  "ZeZtr9n13SWYeGYjyfQCSoGF9cO8jBx/M1aXLigYmxkyQE3QS5VCmEt0+CP7IPrxP07BQmcaCGh9+KUqlTlVvhURebDGuS+PyUZVOT1RPKyUNRiyC9ku7VXvIfA6ljEs8lLGg3LUo2ymZIB6U1E02ZoaQHAK7ub4Tkgn9vIC7RmFoCcuDQzn6gtw7s5rFc+7PcrmXIBUwRxHydw3b1KeQJnsW5oDV3W4Nft/umHcuYiFnw162Eg+PhHI8G9mo3+Sk6zTA0TddwgEci+ApCmxh5hYZdWyHX248wyKqpVyhGD4/Iwsjy/yxZHIzAbg5l2hdfDR93q0UdK3bnT2kJak3ag2vHK0B4G486InL0n0BEI8w+y3vhj7A1iL5TDa0Ps11/oBTQ3l+V383iIe/y28amm2VZs8J5IZs/1M12JNx+OOFZzlR0asgZ9BMGI4lgTROJpkYL7ZrEKd5mW00GxmzJpc5FsBMVW3EFYXfEEnFS6EdXAwCjB6w7jGXmu0IncDB9Ji/W0uS3H+YQVBrmD2jFpqEClJsmPdaPGdz7a1nVsIz390neM6zQ3yT/dCO3LDxCAk4D/wwLFSGpaGJEADWr58k4PAQLPFDEmom9Ju14l+yBwIeyL01qQ2vGDnzuWNhaZeHXBhGz/bVJhnNocmDQU0qwcG97IdIdU5j/zWtkM="
  file: "makestack-$TRAVIS_OS_NAME"
  skip_cleanup: true
  on:
    tags: true
    condition: '$TRAVIS_PYTHON_VERSION == "3.4" || $TRAVIS_OS_NAME == "osx"'
