import makestack.commands.new
import makestack.commands.config
import makestack.commands.env
import makestack.commands.log
import makestack.commands.login
import makestack.commands.register
import makestack.commands.setup_device
import makestack.commands.devices
import makestack.commands.deploy
import makestack.commands.deploy_image
