#!/bin/sh
set -u

cd server
export RAILS_ENV=development
bundle exec rails server -p 31313 2>&1 &
bundle exec sidekiq -C config/sidekiq.yml 2>&1 &
cd ..

sleep 5
make test
result=$?

if [ $result != 0 ]; then
    cat server/log/development.log
fi

kill $(jobs -p)
wait $result
