#!/bin/sh
set -ue
git clone https://github.com/makestack/server
cp ci/database.yml server/config/database.yml
cd server
bundle install --jobs 2 --without mysql sqlite3
RAILS_ENV=development bundle exec rails db:setup
